# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:27
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20170425_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, validators=[django.core.validators.EmailValidator(whitelist=['abakus.no'])])),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email.EmailAddress')),
                ('groups', models.ManyToManyField(related_name='email_lists', to='users.AbakusGroup')),
                ('users', models.ManyToManyField(related_name='email_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
