# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:33
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator(whitelist=['abakus.no'])]),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='email_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_list', to='email.EmailAddress'),
        ),
    ]
