# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20170427_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator(whitelist=['abakus.no'])]),
        ),
    ]
