# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 15:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20170828_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='group_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('member', 'member'), ('leader', 'leader'), ('co-leader', 'co-leader'), ('treasurer', 'treasurer')], max_length=64), default=['member'], size=None),
            preserve_default=False,
        ),
    ]
