# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:25
from __future__ import unicode_literals

import re

import django.core.validators
from django.db import migrations, models

import lego.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0004_auto_20170504_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex=re.compile('(^[-!#$%&\'*+/=?^_`{}|~0-9A-Z]+(\\.[-!#$%&\'*+/=?^_`{}|~0-9A-Z]+)*\\Z|^"([\\001-\\010\\013\\014\\016-\\037!#-\\[\\]-\\177]|\\\\[\\001-\\011\\013\\014\\016-\\177])*"\\Z)', 34)), lego.utils.validators.ReservedNameValidator()]),
        ),
    ]
