# Generated by Django 2.1.2 on 2018-10-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("email", "0005_auto_20171017_1157")]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="require_internal_address",
            field=models.BooleanField(
                default=False,
                help_text="Only allow users with emails from our internal domain, @abakus.no",
            ),
        )
    ]
