# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0005_auto_20170809_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='name',
            field=models.CharField(default='EmailList', max_length=64),
            preserve_default=False,
        ),
    ]
