# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0006_emaillist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='email_address',
            new_name='email',
        ),
    ]
