# Generated by Django 2.1.11 on 2019-09-04 17:16

from django.db import migrations, models
import lego.apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0006_emaillist_require_internal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='additional_emails',
            field=models.EmailField(default='', error_messages={'unique': 'A user with that email already exists.'}, max_length=254, validators=[lego.apps.users.validators.EmailValidatorWithBlacklist(blacklist=['abakus.no'])]),
        ),
    ]
