# Generated by Django 2.2.13 on 2021-03-23 22:20

import django.contrib.postgres.fields
from django.db import migrations, models

import lego.apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("email", "0007_emaillist_additional_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="additional_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(
                    default="",
                    max_length=254,
                    validators=[
                        lego.apps.users.validators.EmailValidatorWithBlacklist(
                            blacklist=["abakus.no"]
                        )
                    ],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
