# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0007_auto_20170809_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='email_list', to='email.EmailAddress'),
        ),
    ]
