# Generated by Django 2.2.19 on 2021-03-26 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0008_auto_20210323_2220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="group_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("member", "member"),
                        ("leader", "leader"),
                        ("co-leader", "co-leader"),
                        ("treasurer", "treasurer"),
                        ("recruiting", "recruiting"),
                        ("development", "development"),
                        ("editor", "editor"),
                        ("retiree", "retiree"),
                        ("media_relations", "media_relations"),
                        ("active_retiree", "active_retiree"),
                        ("alumni", "alumni"),
                        ("webmaster", "webmaster"),
                        ("interest_group_admin", "interest_group_admin"),
                        ("alumni_admin", "alumni_admin"),
                        ("retiree_email", "retiree_email"),
                        ("company_admin", "company_admin"),
                        ("dugnad_admin", "dugnad_admin"),
                        ("trip_admin", "trip_admin"),
                        ("sponsor_admin", "sponsor_admin"),
                        ("social_admin", "social_admin"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
