# Generated by Django 4.2.16 on 2025-10-06 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email", "0011_alter_emaillist_group_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="group_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("member", "member"),
                        ("leader", "leader"),
                        ("co-leader", "co-leader"),
                        ("treasurer", "treasurer"),
                        ("recruiting", "recruiting"),
                        ("development", "development"),
                        ("editor", "editor"),
                        ("retiree", "retiree"),
                        ("media_relations", "media_relations"),
                        ("active_retiree", "active_retiree"),
                        ("alumni", "alumni"),
                        ("webmaster", "webmaster"),
                        ("interest_group_admin", "interest_group_admin"),
                        ("alumni_admin", "alumni_admin"),
                        ("retiree_email", "retiree_email"),
                        ("company_admin", "company_admin"),
                        ("dugnad_admin", "dugnad_admin"),
                        ("trip_admin", "trip_admin"),
                        ("sponsor_admin", "sponsor_admin"),
                        ("social_admin", "social_admin"),
                        ("merch_admin", "merch_admin"),
                        ("hs_representative", "hs_representative"),
                        ("cuddling_manager", "cuddling_manager"),
                        ("photo_admin", "photo_admin"),
                        ("graphic_admin", "graphic_admin"),
                        ("social_media_admin", "social_media_admin"),
                        ("booking_admin", "booking_admin"),
                        ("purchasing_manager", "purchasing_manager"),
                        ("event_manager", "event_manager"),
                        ("snackoverflow_manager", "snackoverflow_manager"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
