
SPRING = 'spring'
AUTUMN = 'autumn'

SEMESTER = (
    (SPRING, SPRING),
    (AUTUMN, AUTUMN),
)


COMPANY_PRESENTATION = 'company_presentation'
COURSE = 'course'
LUNCH_PRESENTATION = 'lunch_presentation'
BEDEX = 'bedex'
OTHER = 'other'

COMPANY_EVENTS = (
    (COMPANY_PRESENTATION, COMPANY_PRESENTATION),
    (COURSE, COURSE),
    (LUNCH_PRESENTATION, LUNCH_PRESENTATION),
    (BEDEX, BEDEX),
    (OTHER, OTHER),
)


INTERESTED = 'interested'
NOT_INTERESTED = 'not_interested'
CONTACTED = 'contacted'
NOT_CONTACTED = 'not_contacted'

SEMESTER_STATUSES = (
    (COMPANY_PRESENTATION, COMPANY_PRESENTATION),
    (COURSE, COURSE),
    (LUNCH_PRESENTATION, LUNCH_PRESENTATION),
    (BEDEX, BEDEX),
    (INTERESTED, INTERESTED),
    (NOT_INTERESTED, NOT_INTERESTED),
    (CONTACTED, CONTACTED),
    (NOT_CONTACTED, NOT_CONTACTED),
)
