# Generated by Django 2.0.2 on 2018-02-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommiteeApplication',
            new_name='CommitteeApplication',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='updated_by',
        ),
    ]
