# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='only_for_invited',
            field=models.BooleanField(default=False),
        ),
    ]
