# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvitation',
            name='status',
            field=models.CharField(choices=[('NO_ANSWER', 'NO_ANSWER'), ('ATTENDING', 'ATTENDING'), ('NOT_ATTENDING', 'NOT_ATTENDING')], default='NO_ANSWER', max_length=50),
        ),
    ]
