# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20170904_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
