# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:17
from __future__ import unicode_literals

from django.db import migrations

import lego.apps.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='images',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='text',
            field=lego.apps.content.fields.ContentField(allow_images=False, blank=True),
        ),
    ]
