# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:20
from __future__ import unicode_literals

from django.db import migrations

import lego.apps.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20171026_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='text',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='report',
            field=lego.apps.content.fields.ContentField(allow_images=False, blank=True),
        ),
    ]
