# Generated by Django 2.1.7 on 2019-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20171210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mazemap_poi',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
