# Generated by Django 2.2.13 on 2021-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_auto_20171210_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
