# Generated by Django 4.2.16 on 2025-03-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_reportchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["is_recurring"], name="meetings_me_is_recu_c79c4f_idx"
            ),
        ),
    ]
