# Generated by Django 5.2.17 on 2026-08-16 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0011_meeting_is_recurring_meeting_is_template_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="_invited_users",
            field=models.ManyToManyField(
                related_name="meeting_invitation",
                through="meetings.MeetingInvitation",
                through_fields=("meeting", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
