# Generated by Django 4.2.16 on 2025-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0011_meeting_is_recurring_meeting_is_template_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_recurring", False), ("is_template", True), _connector="OR"
                ),
                name="recurring_meetings_must_be_templates",
            ),
        ),
    ]
