pipeline:
  tests:
    image: python:3.6
    when:
      event: push
    environment:
      - CASS_DRIVER_NO_CYTHON=1
      - CASS_DRIVER_NO_EXTENSIONS=1
      - LANG=C.UTF-8
    commands:
      - pip install tox
      - pip install -r requirements/test.txt
      - make ci_settings

      - python manage.py migrate
      - python manage.py missing_migrations

      - tox -e tests
      - tox -e isort
      - tox -e flake8
      - tox -e coverage
      - tox -e docs

  docker:
    image: plugins/docker
    when:
      branch:
        - prod
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  deploy:
    image: quay.io/ipedrazas/drone-helm
    when:
      branch:
        - prod
    skip_tls_verify: true
    chart: ./charts/lego
    release: lego-prod
    namespace: lego-prod
    values: |-
      backend.image.tag=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7},backend.config.secret_key='${PROD_SECRET_KEY}',backend.config.database_url='${PROD_DATABASE_URL}',backend.config.cache_url='${PROD_CACHE_URL}',backend.config.email_url='${PROD_EMAIL_URL}',backend.config.sentry='${PROD_SENTRY}',backend.config.celery_broker_url='${PROD_CELERY_BROKER_URL}',backend.config.channels_redis_url='${PROD_CHANNELS_REDIS_URL}',backend.config.stream_redis_host='${PROD_STREAM_REDIS_HOST}',backend.config.stream_redis_db='${PROD_STREAM_REDIS_DB}',backend.config.elasticsearch_host='${PROD_ELASTICSEARCH_HOST}',backend.config.aws_access_key_id='${PROD_AWS_ACCESS_KEY_ID}',backend.config.aws_secret_access_key='${PROD_AWS_SECRET_ACCESS_KEY}',backend.config.aws_region='${PROD_AWS_REGION}',backend.config.aws_s3_bucket='${PROD_AWS_S3_BUCKET}',backend.config.thumbor_server='${PROD_THUMBOR_SERVER}',backend.config.thumbor_security_key='${PROD_THUMBOR_SECURITY_KEY}',backend.config.server_url='${PROD_SERVER_URL}',backend.config.frontend_url='${PROD_FRONTEND_URL}',backend.config.cassandra_hosts='${PROD_CASSANDRA_HOSTS}',backend.config.cassandra_keyspace='${PROD_CASSANDRA_KEYSPACE}',backend.config.stripe_api_key='${PROD_STRIPE_API_KEY}',backend.config.captcha_key='${PROD_CAPTCHA_KEY}',backend.config.ldap_server='${PROD_LDAP_SERVER}',backend.config.ldap_user='${PROD_LDAP_USER}',backend.config.ldap_password='${PROD_LDAP_PASSWORD}'
    wait: true


services:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=lego
  cache:
    image: redis
