pipeline:
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      status: success
      event: push
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
