pipeline:
  setup:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    commands:
      - make ci_settings

  missing-migrations:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
      - DATABASE=database
      - CACHE=cache
    group: testing
    commands:
      - tox -e missing-migrations

  tests:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
      - DATABASE=database
      - CACHE=cache
    group: testing
    commands:
      - tox -e tests

  isort:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e isort

  flake8:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e flake8

  yapf:
    image: abakus/lego-testbase
    pull: true
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e yapf

  docs:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e docs

  coverage:
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    commands:
      - tox -e coverage

  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      status: success
      event: push
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=lego
  cache:
    image: redis
