tasks:
  - tox -e tests
  - tox -e docs
  - tox -e flake8
  - tox -e isort
  - coverage report --fail-under=75
  - coverage xml

services:
  - postgresql

coverage:
  path: coverage.xml
  parser: python
