tasks:
  - tox -e py34
  - tox -e docs
  - flake8
  - isort -c -rc lego
  - coverage report --fail-under=75
  - coverage xml

services:
  - postgresql

coverage:
  path: coverage.xml
  parser: python
