setup_tasks:
  - sudo -u postgres createuser lego -s

tasks:
  - tox -e tests
  - tox -e docs
  - tox -e flake8
  - tox -e isort
  - tox -e coverage

services:
  - postgresql
  - redis-server

coverage:
  path: coverage.xml
  parser: python
