services:

  postgres:
    image: postgres:17
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=lego
      - POSTGRES_HOST_AUTH_METHOD=trust

  lego_cypress_helper:
    image: abakus/lego-cypress-helper:latest
    ports:
      - "127.0.0.1:3030:3030"
    environment:
      PG_HOST: 'postgres'
      PG_USERNAME: 'lego'
      PG_DATABASE: 'lego'
    links:
      - postgres

  garage:
    image: dxflrs/garage:v2.3.0
    ports:
      - '127.0.0.1:9000:3900'
    environment:
      - GARAGE_DEFAULT_ACCESS_KEY=lego-dev
      - GARAGE_DEFAULT_SECRET_KEY=lego-dev-secret-key
      - GARAGE_DEFAULT_BUCKET=lego
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    command: ["/garage", "-c", "/etc/garage.toml", "server", "--single-node", "--default-bucket"]

  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6379:6379'

  thumbor:
    image: minimalcompact/thumbor:6.7.5
    ports:
      - "127.0.0.1:10000:80"
    environment:
      SECURITY_KEY: 'lego-dev'
      MAX_WIDTH: 1000
      MAX_HEIGHT: 800
      MAX_PIXELS: 110000000.0 # 110 million
      QUALITY: 98
      AUTO_WEBP: 'True'
      ALLOW_UNSAFE_URL: 1
      ALLOW_OLD_URLS: 0
      AWS_ACCESS_KEY_ID: 'lego-dev'
      AWS_SECRET_ACCESS_KEY: 'lego-dev-secret-key'
      TC_AWS_LOADER_BUCKET: lego
      TC_AWS_REGION: eu-north-1
      TC_AWS_ENDPOINT: "http://garage:3900"
      LOADER: tc_aws.loaders.s3_loader
