# Generated by Django 2.0.6 on 2018-10-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinned', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedarticle',
            name='pinned_from',
            field=models.DateField(default='2018-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinnedarticle',
            name='pinned_to',
            field=models.DateField(default='2018-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinnedevent',
            name='pinned_from',
            field=models.DateField(default='2018-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinnedevent',
            name='pinned_to',
            field=models.DateField(default='2018-10-11'),
            preserve_default=False,
        ),
    ]
