# Generated by Django 2.0.6 on 2018-10-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinned', '0003_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinned',
            name='article',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='pins', to='articles.Article'
            ),
        ),
        migrations.AlterField(
            model_name='pinned',
            name='event',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='pins', to='events.Event'
            ),
        ),
    ]
