# Generated by Django 2.0.6 on 2018-10-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinned', '0005_auto_20181028_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinned',
            name='article',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='pins', to='articles.Article'
            ),
        ),
        migrations.AlterField(
            model_name='pinned',
            name='event',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='pins', to='events.Event'
            ),
        ),
    ]
