# Generated by Django 2.0.6 on 2018-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinned', '0006_auto_20181031_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinned',
            name='pinned_from',
            field=models.DateField(db_index=True),
        ),
    ]
