# Generated by Django 2.0.6 on 2018-11-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinned', '0007_auto_20181101_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinned',
            name='pinned_from',
            field=models.DateField(),
        ),
    ]
