# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:21
from __future__ import unicode_literals

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='can_edit_groups',
            field=models.ManyToManyField(blank=True, related_name='can_edit_testmodel', to='users.AbakusGroup'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='can_edit_users',
            field=models.ManyToManyField(blank=True, related_name='can_edit_testmodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='can_view_groups',
            field=models.ManyToManyField(blank=True, related_name='can_view_testmodel', to='users.AbakusGroup'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
