# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:58
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20160929_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
