# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_user'),
        ('articles', '0002_auto_20160905_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File'),
        ),
    ]
