# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0002_auto_20160905_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
