# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170126_1435'),
        ('articles', '0004_merge_20170130_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='files.File'),
        ),
    ]
