# Generated by Django 2.0 on 2017-12-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20171026_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(
                default=None, editable=False, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='article_created',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(
                default=None, editable=False, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='article_updated',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
