# Generated by Django 2.1.7 on 2019-03-25 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("articles", "0008_remove_article_author")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="(^(?:https?:\\/\\/)?(?:www[.])?(?:youtube[.]com\\/watch[?]v=|youtu[.]be\\/))"
                    )
                ],
            ),
        )
    ]
