# Generated by Django 2.0.6 on 2018-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pinned',
        ),
    ]
