# Generated by Django 2.1.7 on 2019-03-04 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("articles", "0011_auto_20190304_1903")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="youtube_url",
            field=models.URLField(
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(?:https?://)?(?:www[.])?(?:youtube[.]com/watch[?]v=|youtu[.]be/)([^&]{11})"
                    )
                ],
            ),
        )
    ]
