# Generated by Django 4.2.16 on 2026-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="wiggle",
            field=models.BooleanField(default=False),
        ),
    ]
