# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
