# Generated by Django 2.2.9 on 2020-03-24 18:59

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_auto_20170908_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-ZæøåÆØÅ0-9]+\\Z"),
                        "Enter a valid 'tag' consisting only of letters and numbers.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
