# Generated by Django 4.2.16 on 2025-04-21 16:04

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_auto_20200324_1859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-ZæøåÆØÅ0-9:]+\\Z"),
                        "Enter a valid 'tag' consisting only of letters and numbers.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
