# Generated by Django 5.2.17 on 2026-08-20 16:14

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0005_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^(?:[^\\W_]|[-:])+\\Z"),
                        "Enter a valid 'tag' consisting only of letters, numbers, hyphens and colons.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
