# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='picture',
        ),
        migrations.AddField(
            model_name='page',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_covers', to='files.File'),
        ),
    ]
