# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_auto_20160905_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'flatpage', 'verbose_name_plural': 'flatpages'},
        ),
    ]
