# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_auto_20161018_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='toc',
        ),
    ]
