# Generated by Django 2.1.2 on 2019-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("flatpages", "0005_page_category")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.CharField(
                choices=[
                    ("generelt", "generelt"),
                    ("bedrifter", "bedrifter"),
                    ("arrangementer", "arrangementer"),
                    ("grupper", "grupper"),
                ],
                default="generelt",
                max_length=50,
            ),
        )
    ]
