# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0006_auto_20161229_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
