# Generated by Django 2.2.13 on 2020-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0006_auto_20190222_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.CharField(
                choices=[
                    ("generelt", "generelt"),
                    ("bedrifter", "bedrifter"),
                    ("arrangementer", "arrangementer"),
                    ("grupper", "grupper"),
                    ("personvern", "personvern"),
                ],
                default="generelt",
                max_length=50,
            ),
        ),
    ]
