# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_auto_20161229_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='can_edit_groups',
        ),
        migrations.RemoveField(
            model_name='page',
            name='can_edit_users',
        ),
        migrations.RemoveField(
            model_name='page',
            name='can_view_groups',
        ),
        migrations.RemoveField(
            model_name='page',
            name='require_auth',
        ),
    ]
