# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_auto_20161229_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
