# Generated by Django 2.2.13 on 2020-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0008_auto_20200913_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="require_auth",
            field=models.BooleanField(default=True),
        ),
    ]
