# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0008_auto_20170105_1319'),
        ('flatpages', '0008_auto_20161230_1604'),
    ]

    operations = [
    ]
