# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170126_1435'),
        ('flatpages', '0009_merge_20170105_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_pictures', to='files.File'),
        ),
    ]
