# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0010_page_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='picture',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File'),
        ),
    ]
