# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_public'),
        ('flatpages', '0011_auto_20170423_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='picture',
        ),
        migrations.AddField(
            model_name='page',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_covers', to='files.File'),
        ),
    ]
