NO_ANSWER = 'NO_ANSWER'
ATTENDING = 'ATTENDING'
NOT_ATTENDING = 'NOT_ATTENDING'

INVITATION_STATUS_TYPES = (
    (NO_ANSWER, NO_ANSWER),
    (ATTENDING, ATTENDING),
    (NOT_ATTENDING, NOT_ATTENDING)
)
