# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactiontype',
            old_name='name',
            new_name='short_code',
        ),
        migrations.AddField(
            model_name='reactiontype',
            name='unicode',
            field=models.CharField(db_index=True, default='1F600', max_length=20),
            preserve_default=False,
        ),
    ]
