# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_auto_20161115_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontype',
            name='unicode',
            field=models.CharField(db_index=True, max_length=24),
        ),
    ]
