# Generated by Django 2.1.7 on 2019-09-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emojis", "0001_initial"),
        ("reactions", "0003_auto_20171210_1610"),
    ]

    operations = [
        migrations.RemoveField(model_name="reactiontype", name="created_by"),
        migrations.RemoveField(model_name="reactiontype", name="updated_by"),
        migrations.RemoveField(model_name="reaction", name="type"),
        migrations.AddField(
            model_name="reaction",
            name="emoji",
            field=models.ForeignKey(
                default=":grin:",
                on_delete=django.db.models.deletion.CASCADE,
                to="emojis.Emoji",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="ReactionType"),
    ]
