GENERAL = "generelt"
COMPANIES = "bedrifter"
EVENTS = "arrangementer"
SUB_GROUPS = "undergrupper"
INTEREST_GROUPS = "interessegrupper"

CATEGORIES = ((GENERAL, GENERAL), (COMPANIES, COMPANIES), (EVENTS, EVENTS),
              (SUB_GROUPS, SUB_GROUPS), (INTEREST_GROUPS, INTEREST_GROUPS))
