COMPANY_PRESENTATION = 'company_presentation'
LUNCH_PRESENTATION = 'lunch_presentation'
COURSE = 'course'
KID_EVENT = 'kid_event'
PARTY = 'party'
SOCIAL = 'social'
OTHER = 'other'
EVENT = 'event'

EVENT_TYPES = (
    (COMPANY_PRESENTATION, COMPANY_PRESENTATION),
    (LUNCH_PRESENTATION, LUNCH_PRESENTATION),
    (COURSE, COURSE),
    (KID_EVENT, KID_EVENT),
    (PARTY, PARTY),
    (SOCIAL, SOCIAL),
    (OTHER, OTHER),
    (EVENT, EVENT)
)

UNKNOWN = 'UNKNOWN'
PRESENT = 'PRESENT'
NOT_PRESENT = 'NOT_PRESENT'

PRESENCE_CHOICES = (
    (UNKNOWN, UNKNOWN),
    (PRESENT, PRESENT),
    (NOT_PRESENT, NOT_PRESENT)
)

PENDING_REGISTER = 'PENDING_REGISTER'
SUCCESS_REGISTER = 'SUCCESS_REGISTER'
FAILURE_REGISTER = 'FAILURE_REGISTER'

PENDING_UNREGISTER = 'PENDING_UNREGISTER'
SUCCESS_UNREGISTER = 'SUCCESS_UNREGISTER'
FAILURE_UNREGISTER = 'FAILURE_UNREGISTER'

STATUSES = (
    (PENDING_REGISTER, PENDING_REGISTER),
    (SUCCESS_REGISTER, SUCCESS_REGISTER),
    (FAILURE_REGISTER, FAILURE_REGISTER),
    (PENDING_UNREGISTER, PENDING_UNREGISTER),
    (SUCCESS_UNREGISTER, SUCCESS_UNREGISTER),
    (FAILURE_UNREGISTER, FAILURE_UNREGISTER)
)

PAYMENT_PENDING = 'pending'
PAYMENT_SUCCESS = 'succeeded'
PAYMENT_FAILURE = 'failed'  # Matches stripe API
PAYMENT_MANUAL = 'manual'

SOCKET_PAYMENT_SUCCESS = 'Event.SOCKET_PAYMENT.SUCCESS'
SOCKET_PAYMENT_FAILURE = 'Event.SOCKET_PAYMENT.FAILURE'

SOCKET_REGISTRATION_SUCCESS = 'Event.SOCKET_REGISTRATION.SUCCESS'
SOCKET_REGISTRATION_FAILURE = 'Event.SOCKET_REGISTRATION.FAILURE'
SOCKET_UNREGISTRATION_SUCCESS = 'Event.SOCKET_UNREGISTRATION.SUCCESS'
SOCKET_UNREGISTRATION_FAILURE = 'Event.SOCKET_UNREGISTRATION.FAILURE'

DAYS_BETWEEN_NOTIFY = 1

# Event registration closes a certain amount of hours before the start time
REGISTRATION_CLOSE_TIME = 2
