# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('document', 'document')], default='image', max_length=24),
            preserve_default=False,
        ),
    ]
