# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='token',
            field=models.CharField(default='NnEalx9WDNHWVlYIZyWP265UB6lTFDuS', max_length=32),
            preserve_default=False,
        ),
    ]
