# Generated by Django 4.0.8 on 2022-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_auto_20200907_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="save_for_use",
            field=models.BooleanField(default=False),
        ),
    ]
