# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
