# Generated by Django 2.0.2 on 2018-03-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_survey_sent"),
        ("surveys", "0002_auto_20180221_1905"),
    ]

    operations = []
