# Generated by Django 2.0.4 on 2018-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("surveys", "0003_merge_20180312_1608")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="token",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        )
    ]
