# Generated by Django 2.0.4 on 2018-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("surveys", "0004_survey_token")]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="hide_from_public",
            field=models.BooleanField(default=False),
        )
    ]
