# Generated by Django 2.0.4 on 2018-04-21 16:40

from django.db import migrations, models

import lego.apps.surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='token',
            field=models.CharField(
                default=lego.apps.surveys.models.generate_new_token, max_length=64, unique=True
            ),
        ),
    ]
