# Generated by Django 2.0.4 on 2018-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("surveys", "0005_answer_hide_from_public")]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(blank=True, default=""),
        )
    ]
