# Generated by Django 2.1.7 on 2019-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0006_auto_20180502_1825")]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="template_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company_presentation", "company_presentation"),
                    ("lunch_presentation", "lunch_presentation"),
                    ("alternative_presentation", "alternative_presentation"),
                    ("course", "course"),
                    ("kid_event", "kid_event"),
                    ("party", "party"),
                    ("social", "social"),
                    ("other", "other"),
                    ("event", "event"),
                ],
                max_length=30,
                null=True,
                unique=True,
            ),
        )
    ]
