# Generated by Django 2.1.11 on 2020-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20190714_1906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
