# Generated by Django 2.1.11 on 2020-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0008_question_display_type")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display_type",
            field=models.CharField(
                choices=[("pie_chart", "pie_chart"), ("bar_chart", "bar_chart")],
                default="pie_chart",
                max_length=64,
            ),
        )
    ]
