# Generated by Django 2.1.11 on 2020-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20200212_1821'),
        ('surveys', '0008_question_display_type'),
    ]

    operations = [
    ]
