# Generated by Django 4.2.16 on 2025-02-17 17:20

import django.db.models.deletion
from django.db import migrations, models


def set_is_template(apps, schema_editor):
    Survey = apps.get_model("surveys", "Survey")
    Survey.objects.filter(template_type__isnull=False).update(is_template=True)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_alter_event_event_type"),
        ("surveys", "0012_alter_survey_template_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="survey",
            name="event",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
        ),
        migrations.RunPython(set_is_template),
    ]
