# Generated by Django 4.2.16 on 2025-02-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_alter_event_event_type"),
        ("surveys", "0013_survey_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="event",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
        ),
    ]
