# Generated by Django 4.2.16 on 2025-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0013_survey_is_template_alter_survey_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={},
        ),
    ]
