# Generated by Django 4.2.16 on 2025-03-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0014_alter_survey_template_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={},
        ),
    ]
