# Generated by Django 4.2.16 on 2025-04-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0043_alter_registration_presence_and_more"),
        ("surveys", "0015_alter_survey_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
        ),
    ]
