# Generated by Django 4.2.16 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0018_alter_survey_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="template_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company_presentation", "company_presentation"),
                    ("lunch_presentation", "lunch_presentation"),
                    ("alternative_presentation", "alternative_presentation"),
                    ("course", "course"),
                    ("breakfast_talk", "breakfast_talk"),
                    ("nexus_event", "nexus_event"),
                    ("party", "party"),
                    ("social", "social"),
                    ("gala", "gala"),
                    ("other", "other"),
                    ("event", "event"),
                    ("interest_event", "interest_event"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
