# Generated by Django 4.0.10 on 2024-10-23 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import lego.apps.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0043_alter_abakusgroup_type"),
        ("files", "0005_file_save_for_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="LendableObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("require_auth", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=128)),
                (
                    "can_edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_edit_%(class)s",
                        to="users.abakusgroup",
                    ),
                ),
                (
                    "can_edit_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_edit_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "can_view_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_view_%(class)s",
                        to="users.abakusgroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    lego.apps.files.models.FileField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lendable_object_image",
                        to="files.file",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
