# Generated by Django 4.2.16 on 2025-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendableobject",
            name="contact_email",
            field=models.EmailField(default="webkom@abakus.no", max_length=254),
            preserve_default=False,
        ),
    ]
