# Generated by Django 4.2.16 on 2025-02-27 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_user_achievement_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LendingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("require_auth", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lending_approved", "lending_approved"),
                            ("lending_changes_requested", "lending_changes_requested"),
                            ("lending_denied", "lending_denied"),
                            ("lending_unapproved", "lending_unapproved"),
                        ],
                        default=("lending_unapproved", "lending_unapproved"),
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "can_edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_edit_%(class)s",
                        to="users.abakusgroup",
                    ),
                ),
                (
                    "can_edit_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_edit_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "can_view_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="can_view_%(class)s",
                        to="users.abakusgroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lendable_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lending.lendableobject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_by"], name="lending_len_created_aaa841_idx"
                    ),
                    models.Index(
                        fields=["lendable_object"],
                        name="lending_len_lendabl_4be221_idx",
                    ),
                ],
            },
        ),
    ]
