# Generated by Django 4.0.10 on 2023-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendableobject',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
