# Generated by Django 4.2.16 on 2025-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_lendingrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "approved"),
                    ("cancelled", "cancelled"),
                    ("changes_requested", "changes_requested"),
                    ("denied", "denied"),
                    ("unapproved", "unapproved"),
                ],
                default="unapproved",
            ),
        ),
    ]
