# Generated by Django 4.0.10 on 2024-02-06 20:54

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lego.apps.lending.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending', '0002_lendableobject_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendableobject',
            name='responsible_role',
        ),
        migrations.AddField(
            model_name='lendableobject',
            name='responsible_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('member', 'member'), ('leader', 'leader'), ('co-leader', 'co-leader'), ('treasurer', 'treasurer'), ('recruiting', 'recruiting'), ('development', 'development'), ('editor', 'editor'), ('retiree', 'retiree'), ('media_relations', 'media_relations'), ('active_retiree', 'active_retiree'), ('alumni', 'alumni'), ('webmaster', 'webmaster'), ('interest_group_admin', 'interest_group_admin'), ('alumni_admin', 'alumni_admin'), ('retiree_email', 'retiree_email'), ('company_admin', 'company_admin'), ('dugnad_admin', 'dugnad_admin'), ('trip_admin', 'trip_admin'), ('sponsor_admin', 'sponsor_admin'), ('social_admin', 'social_admin')], max_length=30), default=['member'], size=None, validators=[lego.apps.lending.validators.responsible_roles_validator]),
        ),
        migrations.AlterField(
            model_name='lendableobject',
            name='max_lending_period',
            field=models.DurationField(default=datetime.timedelta(days=7), null=True),
        ),
        migrations.AlterField(
            model_name='lendinginstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendinginstances', to=settings.AUTH_USER_MODEL),
        ),
    ]
