# Generated by Django 4.2.16 on 2025-03-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_lendingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendingrequest",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
