# Generated by Django 4.2.16 on 2025-03-27 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lending", "0003_lendingrequest_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "approved"),
                    ("cancelled", "cancelled"),
                    ("changes_requested", "changes_requested"),
                    ("denied", "denied"),
                    ("unapproved", "unapproved"),
                ],
                default="unapproved",
            ),
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("message", models.TextField()),
                ("is_system", models.BooleanField(blank=True, default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "approved"),
                            ("cancelled", "cancelled"),
                            ("changes_requested", "changes_requested"),
                            ("denied", "denied"),
                            ("unapproved", "unapproved"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lending_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="lending.lendingrequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
    ]
