# Generated by Django 4.0.10 on 2024-02-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_lendableobject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendinginstance',
            name='user',
        ),
    ]
