# Generated by Django 4.2.16 on 2025-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0005_alter_lendingrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "approved"),
                    ("cancelled", "cancelled"),
                    ("changes_requested", "changes_requested"),
                    ("changes_resolved", "changes_resolved"),
                    ("created", "created"),
                    ("denied", "denied"),
                    ("unapproved", "unapproved"),
                ],
                default="unapproved",
            ),
        ),
        migrations.AlterField(
            model_name="timelineentry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "approved"),
                    ("cancelled", "cancelled"),
                    ("changes_requested", "changes_requested"),
                    ("changes_resolved", "changes_resolved"),
                    ("created", "created"),
                    ("denied", "denied"),
                    ("unapproved", "unapproved"),
                ],
                null=True,
            ),
        ),
    ]
