# Generated by Django 4.2.16 on 2025-09-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0006_alter_lendingrequest_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lendingrequest",
            name="text",
        ),
    ]
