# Generated by Django 4.0.10 on 2024-03-12 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0041_user_linkedin_id_alter_user_github_username'),
        ('lending', '0006_lendinginstance_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendableobject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lendinginstance',
            options={},
        ),
        migrations.AddField(
            model_name='lendableobject',
            name='can_edit_groups',
            field=models.ManyToManyField(blank=True, related_name='can_edit_%(class)s', to='users.abakusgroup'),
        ),
        migrations.AddField(
            model_name='lendableobject',
            name='can_edit_users',
            field=models.ManyToManyField(blank=True, related_name='can_edit_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lendableobject',
            name='can_view_groups',
            field=models.ManyToManyField(blank=True, related_name='can_view_%(class)s', to='users.abakusgroup'),
        ),
        migrations.AddField(
            model_name='lendableobject',
            name='require_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lendinginstance',
            name='can_edit_groups',
            field=models.ManyToManyField(blank=True, related_name='can_edit_%(class)s', to='users.abakusgroup'),
        ),
        migrations.AddField(
            model_name='lendinginstance',
            name='can_edit_users',
            field=models.ManyToManyField(blank=True, related_name='can_edit_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lendinginstance',
            name='can_view_groups',
            field=models.ManyToManyField(blank=True, related_name='can_view_%(class)s', to='users.abakusgroup'),
        ),
        migrations.AddField(
            model_name='lendinginstance',
            name='require_auth',
            field=models.BooleanField(default=True),
        ),
    ]
