# Generated by Django 4.2.16 on 2025-10-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0007_remove_lendingrequest_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendableobject",
            name="category",
            field=models.CharField(
                choices=[
                    ("OUTDOORS", "Outdoors"),
                    ("PHOTOGRAPHY", "Photography"),
                    ("INSTRUMENT", "Instrument"),
                    ("SPEAKER", "Speaker"),
                    ("FURNITURE", "Furniture"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=64,
            ),
        ),
    ]
