# Generated by Django 4.2.16 on 2025-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0007_remove_lendingrequest_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendableobject",
            name="category",
            field=models.CharField(
                choices=[
                    ("outdoors", "outdoors"),
                    ("photography", "photography"),
                    ("instrument", "instrument"),
                    ("speaker", "speaker"),
                    ("furniture", "furniture"),
                    ("other", "other"),
                ],
                default="other",
                max_length=64,
            ),
        ),
    ]
