# Generated by Django 4.2.16 on 2025-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0008_lendableobject_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendableobject",
            name="category",
            field=models.CharField(
                choices=[
                    ("outdoors", "outdoors"),
                    ("photography", "photography"),
                    ("music", "music"),
                    ("furniture", "furniture"),
                    ("services", "services"),
                    ("other", "other"),
                ],
                default="other",
                max_length=64,
            ),
        ),
    ]
