# Generated by Django 4.2.16 on 2026-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0009_alter_lendableobject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendingrequest",
            name="archived",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
