# Generated by Django 5.2.17 on 2026-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0010_lendingrequest_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendableobject",
            name="lendable_objects",
            field=models.ManyToManyField(
                blank=True,
                related_name="lendable_bundle_objects",
                to="lending.lendableobject",
            ),
        ),
    ]
