# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_registration_admin_reason'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternative',
            name='alternative_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'radio_button'), (2, 'check_box'), (3, 'text_box')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'single_choice'), (2, 'multiple_choice'), (3, 'text_field')]),
        ),
    ]
