# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 21:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Alternative'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('survey', 'user')]),
        ),
    ]
