# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170427_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_clone',
            field=models.BooleanField(default=False),
        ),
    ]
