# Generated by Django 2.0.2 on 2018-03-07 11:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NotificationFeed',
            fields=[
                ('activity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('feed_id', models.CharField(db_index=True, max_length=64)),
                ('group', models.CharField(max_length=128)),
                ('activity_store', django.contrib.postgres.fields.jsonb.JSONField()),
                ('minimized_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalFeed',
            fields=[
                ('activity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('feed_id', models.CharField(db_index=True, max_length=64)),
                ('group', models.CharField(max_length=128)),
                ('activity_store', django.contrib.postgres.fields.jsonb.JSONField()),
                ('minimized_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('activity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('feed_id', models.CharField(db_index=True, max_length=64)),
                ('group', models.CharField(max_length=128)),
                ('activity_store', django.contrib.postgres.fields.jsonb.JSONField()),
                ('minimized_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
