# Generated by Django 2.0.4 on 2018-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("feeds", "0002_auto_20180411_2018")]

    operations = [
        migrations.AlterModelOptions(
            name="notificationfeed", options={"ordering": ("-id",)}
        ),
        migrations.AlterModelOptions(
            name="personalfeed", options={"ordering": ("-id",)}
        ),
        migrations.AlterModelOptions(name="userfeed", options={"ordering": ("-id",)}),
        migrations.AlterField(
            model_name="timelinestorage",
            name="activity_id",
            field=models.CharField(db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name="timelinestorage",
            name="aggregated_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
