# Generated by Django 3.2.9 on 2021-12-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0006_auto_20181011_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationfeed",
            name="activity_store",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="personalfeed",
            name="activity_store",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="userfeed",
            name="activity_store",
            field=models.JSONField(default=list),
        ),
    ]
