# Generated by Django 2.1.7 on 2019-09-19 19:23

from django.db import migrations


def link_categories(apps, schema_editor):
    Emoji = apps.get_model("emojis", "Emoji")
    Category = apps.get_model("emojis", "Category")
    for emoji in Emoji.objects.all():
        category, created = Category.objects.get_or_create(name=emoji.category)
        emoji.category_link = category
        emoji.save()

    for category in Category.objects.all():
        if category.name == "people":
            category.unicode_string = "😃"
        elif category.name == "animals_and_nature":
            category.unicode_string = "🍃"
        elif category.name == "food_and_drink":
            category.unicode_string = "🍔"
        elif category.name == "activity":
            category.unicode_string = "⚽"
        elif category.name == "travel_and_places":
            category.unicode_string = "✈"
        elif category.name == "objects":
            category.unicode_string = "💡"
        elif category.name == "symbols":
            category.unicode_string = "❤"
        elif category.name == "flags":
            category.unicode_string = "🇵🇱 "
        category.save()


class Migration(migrations.Migration):

    dependencies = [("emojis", "0002_auto_20190919_1922")]

    operations = [migrations.RunPython(link_categories)]
