# Generated by Django 2.1.7 on 2019-09-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("emojis", "0003_transfer_emoji_categories")]

    operations = [migrations.RemoveField(model_name="emoji", name="category")]
