# Generated by Django 2.1.7 on 2019-09-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("emojis", "0004_remove_emoji_category")]

    operations = [
        migrations.RenameField(
            model_name="emoji", old_name="category_link", new_name="category"
        )
    ]
