SINGLE_CHOICE = "single_choice"
MULTIPLE_CHOICE = "multiple_choice"
TEXT_FIELD = "text_field"

QUESTION_TYPES = (
    (SINGLE_CHOICE, SINGLE_CHOICE),
    (MULTIPLE_CHOICE, MULTIPLE_CHOICE),
    (TEXT_FIELD, TEXT_FIELD),
)
