SINGLE_CHOICE = "single_choice"
MULTIPLE_CHOICE = "multiple_choice"
TEXT_FIELD = "text_field"
PIE_CHART = "pie_chart"
BAR_CHART = "bar_chart"

QUESTION_TYPES = (
    (SINGLE_CHOICE, SINGLE_CHOICE),
    (MULTIPLE_CHOICE, MULTIPLE_CHOICE),
    (TEXT_FIELD, TEXT_FIELD),
)

DISPLAY_TYPES = ((PIE_CHART, PIE_CHART), (BAR_CHART, BAR_CHART))
