# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('weekly_mail', 'weekly_mail')], max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'email')], max_length=64), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together=set([('user', 'notification_type')]),
        ),
    ]
