# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'email')], max_length=64), null=True, size=None),
        ),
    ]
