# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170426_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'email')], max_length=64), default=['email'], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
