# Generated by Django 2.0.2 on 2018-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0006_auto_20171210_1610")]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("weekly_mail", "weekly_mail"),
                    ("event_bump", "event_bump"),
                    ("event_admin_registration", "event_admin_registration"),
                    ("event_admin_unregistration", "event_admin_unregistration"),
                    ("event_payment_overdue", "event_payment_overdue"),
                    ("event_payment_overdue_creator", "event_payment_overdue_creator"),
                    ("meeting_invite", "meeting_invite"),
                    ("penalty_creation", "penalty_creation"),
                    ("restricted_mail_sent", "restricted_mail_sent"),
                    ("company_interest_created", "company_interest_created"),
                    ("comment", "comment"),
                    ("comment_reply", "comment_reply"),
                    ("announcement", "announcement"),
                    ("survey_created", "survey_created"),
                ],
                max_length=64,
            ),
        )
    ]
