# Generated by Django 4.0.6 on 2022-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_alter_announcement_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("weekly_mail", "weekly_mail"),
                    ("event_bump", "event_bump"),
                    ("event_admin_registration", "event_admin_registration"),
                    ("event_admin_unregistration", "event_admin_unregistration"),
                    ("event_payment_overdue", "event_payment_overdue"),
                    ("event_payment_overdue_creator", "event_payment_overdue_creator"),
                    ("meeting_invite", "meeting_invite"),
                    ("meeting_invitation_reminder", "meeting_invitation_reminder"),
                    ("penalty_creation", "penalty_creation"),
                    ("restricted_mail_sent", "restricted_mail_sent"),
                    ("company_interest_created", "company_interest_created"),
                    ("comment", "comment"),
                    ("comment_reply", "comment_reply"),
                    ("announcement", "announcement"),
                    ("survey_created", "survey_created"),
                    ("registration_reminder", "registration_reminder"),
                    ("inactive_warning", "inactive_warning"),
                    ("deleted_warning", "deleted_warning"),
                ],
                max_length=64,
            ),
        ),
    ]
