# Generated by Django 4.0.10 on 2024-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0014_alter_notificationsetting_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="exclude_waiting_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meeting_invitation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_ANSWER", "NO_ANSWER"),
                    ("ATTENDING", "ATTENDING"),
                    ("NOT_ATTENDING", "NOT_ATTENDING"),
                ],
                max_length=50,
            ),
        ),
    ]
