# Generated by Django 4.0.10 on 2024-03-12 18:14

import django.contrib.postgres.fields
from django.db import migrations, models

import lego.apps.notifications.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0015_announcement_exclude_waiting_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="channels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("email", "email"), ("push", "push")], max_length=64
                ),
                blank=True,
                default=lego.apps.notifications.models._default_channels,
                null=True,
                size=None,
            ),
        ),
    ]
