# Generated by Django 4.0.10 on 2024-03-12 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0015_alter_notificationsetting_notification_type"),
        ("notifications", "0015_announcement_exclude_waiting_list_and_more"),
    ]

    operations = []
