# Generated by Django 4.0.10 on 2024-04-23 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0016_alter_notificationsetting_channels"),
        ("notifications", "0016_merge_20240312_1850"),
    ]

    operations = []
