# Generated by Django 4.2.16 on 2025-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_alter_notificationsetting_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
