# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160406_1835'),
        ('articles', '0002_auto_20160119_1808'),
    ]

    operations = [
    ]
