# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160119_1808'),
        ('articles', '0004_auto_20160421_0001'),
    ]

    operations = [
    ]
