SOCKET_ADD_SUCCESS = "Comment.SOCKET_ADD.SUCCESS"
SOCKET_ADD_FAILURE = "Comment.SOCKET_ADD.FAILURE"
SOCKET_DELETE_SUCCESS = "Comment.SOCKET_DELETE.SUCCESS"
SOCKET_DELETE_FAILURE = "Comment.SOCKET_DELETE.FAILURE"
