# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:20
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
