# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 15:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20161119_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
        ),
    ]
