# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 17:53
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='interestgroup',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
