# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user'),
        ('social_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='logo',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_logos', to='files.File'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='logo',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interestgroup_logos', to='files.File'),
        ),
    ]
