# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('social_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='interestgroup',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
