# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_groups', '0002_auto_20170905_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='interestgroup',
            name='logo',
        ),
    ]
