# Generated by Django 4.2.16 on 2024-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_alter_achievement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="identifier",
            field=models.CharField(
                choices=[
                    ("event_count", "event_count"),
                    ("event_price", "event_price"),
                    ("event_rank", "event_rank"),
                    ("meeting_hidden", "meeting_hidden"),
                    ("penalty_period", "penalty_period"),
                    ("poll_count", "poll_count"),
                    ("quote_count", "quote_count"),
                ],
                max_length=128,
            ),
        ),
    ]
