# Generated by Django 4.2.16 on 2025-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0008_alter_achievement_identifier"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="achievement",
            name="unique_user_identifier",
        ),
        migrations.RemoveIndex(
            model_name="achievement",
            name="achievement_user_id_58535a_idx",
        ),
        migrations.AddConstraint(
            model_name="achievement",
            constraint=models.UniqueConstraint(
                fields=("user", "identifier", "level"), name="unique_user_identifier"
            ),
        ),
    ]
