# Generated by Django 4.2.16 on 2025-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0009_remove_achievement_unique_user_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="identifier",
            field=models.CharField(
                choices=[
                    ("christmas_calendar", "christmas_calendar"),
                    ("complete_profile", "complete_profile"),
                    ("easter_winner", "easter_winner"),
                    ("event_count", "event_count"),
                    ("event_price", "event_price"),
                    ("event_rank", "event_rank"),
                    ("event_rules", "event_rules"),
                    ("gala_count", "gala_count"),
                    ("genfors_count", "genfors_count"),
                    ("keypress_order", "keypress_order"),
                    ("meeting_hidden", "meeting_hidden"),
                    ("penalty_period", "penalty_period"),
                    ("poll_count", "poll_count"),
                    ("quote_count", "quote_count"),
                ],
                max_length=128,
            ),
        ),
    ]
