# Generated by Django 5.2.17 on 2026-08-27 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0011_split_easter_achievement_identifiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RankSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("achievement_score", "Achievement score"),
                            ("event_count", "Event count"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("value", models.FloatField()),
                ("date", models.DateField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "type", "date"],
                        name="achievement_user_id_10f8a9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type", "date"),
                        name="unique_user_type_rank_date",
                    )
                ],
            },
        ),
    ]
