# Generated by Django 5.2.17 on 2026-08-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0012_ranksnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="identifier",
            field=models.CharField(
                choices=[
                    ("christmas_calendar", "christmas_calendar"),
                    ("complete_profile", "complete_profile"),
                    ("easter_2024", "easter_2024"),
                    ("easter_2025", "easter_2025"),
                    ("easter_2026", "easter_2026"),
                    ("event_count", "event_count"),
                    ("event_price", "event_price"),
                    ("event_rank", "event_rank"),
                    ("event_rules", "event_rules"),
                    ("gala_count", "gala_count"),
                    ("genfors_count", "genfors_count"),
                    ("keypress_order", "keypress_order"),
                    ("meeting_hidden", "meeting_hidden"),
                    ("penalty_period", "penalty_period"),
                    ("perfect_week", "perfect_week"),
                    ("poll_count", "poll_count"),
                    ("quote_count", "quote_count"),
                ],
                max_length=128,
            ),
        ),
    ]
