# Generated by Django 5.2.17 on 2026-09-11 20:44

from collections import defaultdict

from django.db import migrations, models


def backfill_active_history(apps, schema_editor):
    from lego.apps.achievements.constants import RankType
    from lego.apps.achievements.models import RankSnapshot
    from lego.apps.achievements.ranking import _compute_ranks, filter_active_users
    from lego.apps.users.models import User

    active_user_ids = set(
        filter_active_users(User.objects.all()).values_list("id", flat=True)
    )

    type_pairs = (
        (RankType.ACHIEVEMENT_SCORE, RankType.ACHIEVEMENT_SCORE_ACTIVE),
        (RankType.EVENT_COUNT, RankType.EVENT_COUNT_ACTIVE),
    )
    for base_type, active_type in type_pairs:
        rows_by_date = defaultdict(list)
        for date, user_id, value in RankSnapshot.objects.filter(
            type=base_type, user_id__in=active_user_ids
        ).values_list("date", "user_id", "value"):
            rows_by_date[date].append((user_id, value))

        current_value_by_user = {}
        latest_rank_by_user = {}
        to_create = []
        for date in sorted(rows_by_date):
            for user_id, value in rows_by_date[date]:
                current_value_by_user[user_id] = value

            ordered = sorted(current_value_by_user.items(), key=lambda pair: -pair[1])
            for user_id, rank, value in _compute_ranks(ordered):
                if latest_rank_by_user.get(user_id) != rank:
                    to_create.append(
                        RankSnapshot(
                            user_id=user_id,
                            type=active_type,
                            rank=rank,
                            value=value,
                            date=date,
                        )
                    )
                latest_rank_by_user[user_id] = rank

        RankSnapshot.objects.filter(type=active_type).delete()
        RankSnapshot.objects.bulk_create(to_create)


def remove_active_history(apps, schema_editor):
    RankSnapshot = apps.get_model("achievements", "RankSnapshot")
    RankSnapshot.objects.filter(
        type__in=["achievement_score_active", "event_count_active"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0013_alter_achievement_identifier"),
        ("users", "0056_alter_user_abakus_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranksnapshot",
            name="type",
            field=models.CharField(
                choices=[
                    ("achievement_score", "Achievement score"),
                    ("achievement_score_active", "Achievement score (active)"),
                    ("event_count", "Event count"),
                    ("event_count_active", "Event count (active)"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_active_history, remove_active_history),
    ]
