# Generated by Django 2.0.6 on 2018-10-10 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="authors",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        )
    ]
