# Generated by Django 2.0.6 on 2018-10-17 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("podcasts", "0003_auto_20181016_2221")]

    operations = [migrations.RemoveField(model_name="podcast", name="title")]
