# Generated by Django 2.1.5 on 2019-01-11 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20181107_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='poll',
            name='answered_users',
            field=models.ManyToManyField(related_name='answered_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 7, 3, 42540, tzinfo=utc)),
        ),
    ]
