# Generated by Django 2.1.5 on 2019-01-11 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 7, 49, 297080, tzinfo=utc)),
        ),
    ]
