apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: {{ template "fullname" . }}-api
