# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 14:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170903_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_covers', to='gallery.GalleryPicture'),
        ),
    ]
