# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_public'),
        ('gallery', '0003_auto_20170714_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypicture',
            options={},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='photographers_users',
            new_name='photographers',
        ),
        migrations.AlterUniqueTogether(
            name='gallerypicture',
            unique_together=set([('gallery', 'file')]),
        ),
    ]
