# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170910_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypicture',
            name='taggees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
