# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170714_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypicture',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallerypicture',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
