# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170714_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypicture',
            name='deleted',
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_covers', to='gallery.GalleryPicture'),
        ),
    ]
