# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_public'),
        ('gallery', '0005_auto_20170714_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_covers', to='files.File'),
        ),
    ]
