# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170714_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypicture',
            name='deleted',
        ),
    ]
