# Generated by Django 4.2.16 on 2026-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_alter_gallery_can_edit_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
