# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 20:06
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20161210_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apiapplication',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
