# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160129_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ingress',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
