# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20160204_1725'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='can_edit_groups',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='can_edit_users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='can_view_groups',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='require_auth',
        ),
    ]
