# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20151105_2217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_auto_20160406_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='can_edit_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='can_edit_comment', to='users.AbakusGroup'),
        ),
        migrations.AddField(
            model_name='comment',
            name='can_edit_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='can_edit_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='can_view_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='can_view_comment', to='users.AbakusGroup'),
        ),
        migrations.AddField(
            model_name='comment',
            name='require_auth',
            field=models.BooleanField(default=False, verbose_name='require auth'),
        ),
    ]
