# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20160406_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='can_edit_groups',
            field=models.ManyToManyField(blank=True, related_name='can_edit_comment', to='users.AbakusGroup'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='can_edit_users',
            field=models.ManyToManyField(blank=True, related_name='can_edit_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='can_view_groups',
            field=models.ManyToManyField(blank=True, related_name='can_view_comment', to='users.AbakusGroup'),
        ),
    ]
