# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterstatus',
            name='bedex',
        ),
        migrations.AlterField(
            model_name='semesterstatus',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Vår'), (1, 'Høst'), (2, 'Bedex')], default=0),
        ),
    ]
