# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterstatus',
            name='contacted_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bedpres'), (1, 'Bedpres & Kurs'), (2, 'Kurs'), (3, 'Interested, not offered'), (4, 'Not interested'), (5, 'Contacted'), (6, 'Not Contacted')], default=6),
        ),
        migrations.AlterField(
            model_name='semesterstatus',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Spring'), (1, 'Fall'), (2, 'Bedex')], default=0),
        ),
    ]
