# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170126_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterstatus',
            name='contacted_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Company presentation'), (1, 'Company presentation & course'), (2, 'Course'), (3, 'Interested, not offered'), (4, 'Not interested'), (5, 'Contacted'), (6, 'Not Contacted')], default=6),
        ),
    ]
