# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170919_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='student_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
