# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170126_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_mail',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
