# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 00:35
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_auto_20170127_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('events', models.CommaSeparatedIntegerField(choices=[(0, 'Company presentation'), (1, 'Course'), (3, 'Lunch presentation'), (5, 'Bedex'), (4, 'Jubileum'), (2, 'Other')], max_length=30)),
                ('readMe', models.BooleanField()),
                ('collaboration', models.BooleanField()),
                ('itdagene', models.BooleanField()),
                ('comment', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyinterest_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('year', models.PositiveIntegerField()),
                ('spring', models.BooleanField()),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='companyinterest',
            name='semesters',
            field=models.ManyToManyField(to='companies.Semester'),
        ),
        migrations.AddField(
            model_name='companyinterest',
            name='updated_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyinterest_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
