# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20170127_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='student_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
