# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170919_1830'),
        ('companies', '0007_auto_20170922_0203'),
    ]

    operations = [
    ]
