# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20170311_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='can_edit_groups',
        ),
        migrations.RemoveField(
            model_name='company',
            name='can_edit_users',
        ),
        migrations.RemoveField(
            model_name='company',
            name='can_view_groups',
        ),
        migrations.RemoveField(
            model_name='company',
            name='require_auth',
        ),
    ]
