# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20170311_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinterest',
            name='events',
            field=models.CharField(max_length=100),
        ),
    ]
