# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20170313_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='semesterstatus',
            name='contacted_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Company presentation'), (1, 'Company presentation & course'), (2, 'Course'), (3, 'Interested, not offered'), (4, 'Not interested'), (5, 'Contacted'), (6, 'Not Contacted'), (7, 'BedEx')], default=6),
        ),
    ]
