# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20170311_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinterest',
            name='collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyinterest',
            name='itdagene',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyinterest',
            name='readMe',
            field=models.BooleanField(default=False),
        ),
    ]
