# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20171003_1443'),
        ('companies', '0010_auto_20170930_1336'),
    ]

    operations = [
    ]
