# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20171012_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinterest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyinterest',
            name='updated_by',
        ),
    ]
