# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20170311_2350'),
        ('companies', '0007_auto_20170311_1554'),
    ]

    operations = [
    ]
