# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_merge_20171004_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
