# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20171012_1555'),
        ('companies', '0011_auto_20171013_0822'),
    ]

    operations = [
    ]
