# Generated by Django 2.0.6 on 2018-10-01 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20171210_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinterest',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('company_presentation', 'company_presentation'), ('course', 'course'),
                        ('lunch_presentation', 'lunch_presentation'), ('bedex', 'bedex'),
                        ('other', 'other'), ('sponsor', 'sponsor')
                    ], max_length=64
                ), size=None
            ),
        ),
    ]
