# Generated by Django 2.1.11 on 2020-02-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0016_auto_20190128_1914")]

    operations = [
        migrations.AddField(
            model_name="companyinterest",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_interests",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="phone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="companyinterest",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
