# Generated by Django 2.2.13 on 2020-09-27 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_auto_20200224_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("course", "course"),
                        ("digital_presentation", "digital_presentation"),
                        ("bedex", "bedex"),
                        ("other", "other"),
                        ("sponsor", "sponsor"),
                        ("start_up", "start_up"),
                    ],
                    max_length=64,
                ),
                size=None,
            ),
        ),
    ]
