# Generated by Django 2.2.20 on 2021-08-28 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0018_auto_20200927_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("course", "course"),
                        ("digital_presentation", "digital_presentation"),
                        ("bedex", "bedex"),
                        ("other", "other"),
                        ("sponsor", "sponsor"),
                        ("start_up", "start_up"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="companyinterest",
            name="other_offers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("collaboration", "collaboration"),
                        ("readme", "readme"),
                        ("itdagene", "itdagene"),
                        ("labamba_sponsor", "labamba_sponsor"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
