# Generated by Django 2.2.20 on 2021-10-05 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0019_auto_20210828_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinterest",
            name="collaborations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("collaboration_online", "collaboration_online"),
                        ("collaboration_omega", "collaboration_omega"),
                        ("collaboration_revue", "collaboration_revue"),
                        ("collaboration_anniversary", "collaboration_anniversary"),
                        (
                            "collaboration_revue_anniversary",
                            "collaboration_revue_anniversary",
                        ),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="participant_range_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="participant_range_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="second_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="target_grades",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
