# Generated by Django 3.2.10 on 2022-02-22 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0020_auto_20211005_2128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="collaborations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("collaboration_online", "collaboration_online"),
                        ("collaboration_omega", "collaboration_omega"),
                        ("collaboration_tihlde", "collaboration_tihlde"),
                        ("collaboration_revue", "collaboration_revue"),
                        ("collaboration_anniversary", "collaboration_anniversary"),
                        (
                            "collaboration_revue_anniversary",
                            "collaboration_revue_anniversary",
                        ),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="companyinterest",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("course", "course"),
                        ("digital_presentation", "digital_presentation"),
                        ("bedex", "bedex"),
                        ("other", "other"),
                        ("sponsor", "sponsor"),
                        ("start_up", "start_up"),
                        ("company_to_company", "company_to_company"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
