# Generated by Django 4.0.6 on 2022-08-22 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0024_alter_company_created_by_alter_company_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("course", "course"),
                        ("breakfast_talk", "breakfast_talk"),
                        ("digital_presentation", "digital_presentation"),
                        ("bedex", "bedex"),
                        ("other", "other"),
                        ("sponsor", "sponsor"),
                        ("start_up", "start_up"),
                        ("company_to_company", "company_to_company"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="semesterstatus",
            name="contacted_status",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("course", "course"),
                        ("breakfast_talk", "breakfast_talk"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("bedex", "bedex"),
                        ("contact_in_oslo", "contact_in_oslo"),
                        ("interested", "interested"),
                        ("not_interested", "not_interested"),
                        ("contacted", "contacted"),
                        ("not_contacted", "not_contacted"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
