# Generated by Django 4.0.6 on 2022-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0025_alter_companyinterest_events_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyinterest",
            old_name="second_comment",
            new_name="other_event_comment",
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="breakfast_talk_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="course_comment",
            field=models.TextField(blank=True),
        ),
    ]
