# Generated by Django 4.0.9 on 2023-02-21 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0026_rename_second_comment_companyinterest_other_event_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinterest",
            name="bedex_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="company_course_themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_survey_security", "Security"),
                        ("company_survey_ai", "Ai"),
                        ("company_survey_big_data", "Data"),
                        ("company_survey_front_back_end", "End"),
                        ("company_survey_iot", "Iot"),
                        ("company_survey_gamedev", "Gamedev"),
                        ("company_survey_softskills", "Softskills"),
                        ("company_survey_fintech", "Fintech"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="company_presentation_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="company_to_company_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company_types_small_consultant", "Small Consultant"),
                    ("company_types_medium_consultant", "Medium Consultant"),
                    ("company_types_large_consultant", "Large Consultant"),
                    ("company_types_inhouse", "Inhouse"),
                    ("company_types_others", "Types Others"),
                    ("company_types_start_up", "Start Up"),
                    ("company_types_governmental", "Governmental"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="lunch_presentation_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="office_in_trondheim",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="companyinterest",
            name="startup_comment",
            field=models.TextField(blank=True),
        ),
    ]
