# Generated by Django 4.0.10 on 2024-09-25 18:53

from django.db import migrations
from django.conf import settings


def create_comment_with_old_admin_comment(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Comment = apps.get_model("comments", "Comment")
    CompanyContentType = apps.get_model("contenttypes", "ContentType").objects.get(
        model="company"
    )

    for c in Company.objects.all():
        if c.admin_comment != None:
            Comment.objects.create(
                text="Autogenerert kommentar fra gammelt notat: \n" + c.admin_comment,
                content_type=CompanyContentType,
                object_id=c.id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_companyinterest_other_offers'),
        ('comments', '0008_alter_comment_created_by_alter_comment_updated_by'),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_comment_with_old_admin_comment),
        migrations.RemoveField(
            model_name="company",
            name="admin_comment",
        ),
    ]
