# Generated by Django 4.0.10 on 2025-02-12 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0029_remove_company_previous_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="other_offers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("collaboration", "collaboration"),
                        ("readme", "readme"),
                        ("itdagene", "itdagene"),
                        ("labamba_sponsor", "labamba_sponsor"),
                        ("social_media", "social_media"),
                        ("thursday_event", "thursday_event"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
