# Generated by Django 4.2.16 on 2024-11-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0029_remove_company_previous_contacts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInterestEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("company_presentation", "company_presentation"),
                            ("lunch_presentation", "lunch_presentation"),
                            ("course", "course"),
                            ("breakfast_talk", "breakfast_talk"),
                            ("digital_presentation", "digital_presentation"),
                            ("bedex", "bedex"),
                            ("other", "other"),
                            ("sponsor", "sponsor"),
                            ("start_up", "start_up"),
                            ("company_to_company", "company_to_company"),
                        ],
                        max_length=64,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "company_interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_events",
                        to="companies.companyinterest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="companyinterestevent",
            constraint=models.UniqueConstraint(
                fields=("company_interest", "name"),
                name="unique_company_interest_event_name",
            ),
        ),
    ]
