# Generated by Django 4.2.16 on 2024-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0029_remove_company_previous_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company_types_small_consultant", "Small Consultant"),
                    ("company_types_medium_consultant", "Medium Consultant"),
                    ("company_types_large_consultant", "Large Consultant"),
                    ("company_types_inhouse", "In House"),
                    ("company_types_others", "Types Others"),
                    ("company_types_start_up", "Start Up"),
                    ("company_types_governmental", "Governmental"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyinterest",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company_types_small_consultant", "Small Consultant"),
                    ("company_types_medium_consultant", "Medium Consultant"),
                    ("company_types_large_consultant", "Large Consultant"),
                    ("company_types_inhouse", "In House"),
                    ("company_types_others", "Types Others"),
                    ("company_types_start_up", "Start Up"),
                    ("company_types_governmental", "Governmental"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
