# Generated by Django 4.2.16 on 2024-12-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0029_remove_company_previous_contacts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"]},
        ),
    ]
