# Generated by Django 4.2.16 on 2024-11-02 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0029_remove_company_previous_contacts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInterestEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("company_presentation", "company_presentation"),
                            ("lunch_presentation", "lunch_presentation"),
                            ("course", "course"),
                            ("breakfast_talk", "breakfast_talk"),
                            ("digital_presentation", "digital_presentation"),
                            ("bedex", "bedex"),
                            ("other", "other"),
                            ("sponsor", "sponsor"),
                            ("start_up", "start_up"),
                            ("company_to_company", "company_to_company"),
                        ],
                        max_length=64,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "company_interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companyinterest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="companyinterestevent",
            constraint=models.UniqueConstraint(
                fields=("company_interest", "event"),
                name="unique_company_interest_event",
            ),
        ),
    ]
