# Generated by Django 4.0.10 on 2024-10-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_remove_company_previous_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcompanycontact',
            old_name='student',
            new_name='user',
        ),
    ]
