# Generated by Django 4.2.16 on 2025-02-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0031_rename_student_studentcompanycontact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="admin_comment",
        ),
    ]
