# Generated by Django 4.2.16 on 2025-01-22 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0031_rename_student_studentcompanycontact_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinterest",
            name="collaborations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("collaboration_online", "collaboration_online"),
                        ("collaboration_omega", "collaboration_omega"),
                        ("collaboration_tihlde", "collaboration_tihlde"),
                        ("collaboration_anniversary", "collaboration_anniversary"),
                        (
                            "collaboration_revue_anniversary",
                            "collaboration_revue_anniversary",
                        ),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="companyinterest",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("company_presentation", "company_presentation"),
                        ("lunch_presentation", "lunch_presentation"),
                        ("course", "course"),
                        ("breakfast_talk", "breakfast_talk"),
                        ("digital_presentation", "digital_presentation"),
                        ("bedex", "bedex"),
                        ("other", "other"),
                        ("sponsor", "sponsor"),
                        ("company_to_company", "company_to_company"),
                    ],
                    max_length=64,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
