# Generated by Django 4.2.16 on 2025-03-26 17:33

from django.db import migrations, models


def migrate_thursday_event(apps, schema_editor):
    CompanyInterest = apps.get_model("companies", "CompanyInterest")
    company_interests = CompanyInterest.objects.filter(
        other_offers__contains=["thursday_event"]
    )
    for company_interest in company_interests:
        company_interest.other_offers.remove("thursday_event")
        company_interest.wants_thursday_event = True
        company_interest.save()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0033_alter_companyinterest_other_offers"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinterest",
            name="wants_thursday_event",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunPython(migrate_thursday_event),
    ]
