# Generated by Django 4.2.16 on 2026-03-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0034_companyinterest_wants_thursday_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semesterstatus",
            options={"ordering": ["-semester_id"]},
        ),
    ]
