# Generated by Django 5.2.17 on 2026-10-08 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0035_alter_semesterstatus_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="active",
        ),
    ]
