# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
    ]
