# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
    ]
