# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170126_1435'),
        ('quotes', '0004_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='images',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
