# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20171019_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
    ]
