# Generated by Django 2.0.6 on 2018-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20171210_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='pinned',
        ),
    ]
