# Generated by Django 4.2.16 on 2025-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_alter_quote_created_by_alter_quote_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
