# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_auto_20161207_1230'),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowEvent',
            fields=[
                ('follower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='followers.Follower')),
                ('followed_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='events.Event')),
            ],
            options={
                'default_manager_name': 'objects',
                'abstract': False,
            },
            bases=('followers.follower',),
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('follower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='followers.Follower')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_manager_name': 'objects',
                'abstract': False,
            },
            bases=('followers.follower',),
        ),
        migrations.RemoveField(
            model_name='follower',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='object_id',
        ),
    ]
