# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_merge_20170127_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followevent',
            unique_together=set([('follower', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together=set([('follower', 'target')]),
        ),
    ]
