# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_auto_20170127_1727'),
        ('followers', '0002_auto_20170130_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='followcompany',
            unique_together=set([('follower', 'target')]),
        ),
    ]
