# Generated by Django 2.2.9 on 2020-03-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("followers", "0003_followevent_sent")]

    operations = [
        migrations.RenameField(
            model_name="followevent", old_name="sent", new_name="notification_sent"
        )
    ]
