# Generated by Django 4.0.10 on 2024-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='sticky',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='sticky',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
