# Generated by Django 4.2.16 on 2025-09-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="can_edit_groups",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="can_edit_users",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="can_view_groups",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="Forum",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
