# Generated by Django 4.0.10 on 2024-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forum_sticky_thread_locked_thread_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='sticky',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='sticky',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
