# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20160610_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_manager_name': 'objects'},
        ),
    ]
