# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:17
from __future__ import unicode_literals

from django.db import migrations

import lego.apps.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=lego.apps.content.fields.ContentField(allow_images=False),
        ),
    ]
