# Generated by Django 2.1.7 on 2019-03-06 15:08

from django.db import migrations

import lego.apps.content.fields


class Migration(migrations.Migration):

    dependencies = [("comments", "0006_auto_20180207_1611")]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=lego.apps.content.fields.ContentField(allow_images=False, null=True),
        )
    ]
