# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_registration_waiting_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pool',
            options={'default_manager_name': 'objects'},
        ),
    ]
