# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
