# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 20:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=lego.apps.files.models.FileField(default='test_event_cover.png', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_covers', to='files.File'),
        ),
    ]
