# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='admin_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
