# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_author'),
        ('events', '0003_auto_20160929_1421'),
    ]

    operations = [
    ]
