# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_feedback_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_due_date',
        ),
        migrations.AddField(
            model_name='event',
            name='payment_due_days',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
