# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20161018_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='heed_penalties',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='penalty_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='penalty_weight_on_not_present',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
