# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='unregistration_deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='unregistration_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
