# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_pool_unregistration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_priced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_user',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='price_guest',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='price_member',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='charge_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
