# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_registration_status'),
        ('events', '0010_auto_20161115_2210'),
    ]

    operations = [
    ]
