# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING_REGISTER', 'PENDING_REGISTER'), ('SUCCESS_REGISTER', 'SUCCESS_REGISTER'), ('FAILURE_REGISTER', 'FAILURE_REGISTER'), ('PENDING_UNREGISTER', 'PENDING_UNREGISTER'), ('SUCCESS_UNREGISTER', 'SUCCESS_UNREGISTER'), ('FAILURE_UNREGISTER', 'FAILURE_UNREGISTER')], default='PENDING_REGISTER', max_length=20),
        ),
    ]
