# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_20161119_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='charge_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
