# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_registration_charge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_tickets_per_user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ticket_count',
        ),
    ]
