# Generated by Django 2.0.2 on 2018-02-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20171210_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
    ]
