# Generated by Django 2.0.2 on 2018-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20171210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_abakom_only',
            field=models.BooleanField(default=False),
        ),
    ]
