# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20161121_1411'),
        ('events', '0012_auto_20161122_1605'),
    ]

    operations = [
    ]
