# Generated by Django 2.1.2 on 2018-10-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0016_auto_20180223_1614")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_close_time",
            field=models.PositiveIntegerField(default=2),
        )
    ]
