# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20161203_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='charge_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='charge_amount_refunded',
            field=models.IntegerField(default=0),
        ),
    ]
