# Generated by Django 2.0.6 on 2018-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180223_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pinned',
        ),
    ]
