# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('events', '0017_auto_20161207_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.Company'),
        ),
    ]
