# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20161207_1230'),
        ('events', '0008_event_tags'),
    ]

    operations = [
    ]
