# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_user'),
        ('events', '0017_auto_20161207_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File'),
        ),
    ]
