# Generated by Django 2.1.2 on 2018-11-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20181024_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hours_before_registration_close_time',
            new_name='registration_deadline_hours',
        ),
    ]
