# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_merge_20170127_1138'),
        ('events', '0018_event_tags'),
    ]

    operations = [
    ]
