# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_merge_20170130_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feedback_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='feedback',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
