# Generated by Django 2.1.7 on 2019-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0020_auto_20190302_1309")]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="photo_consent",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("PHOTO_CONSENT", "PHOTO_CONSENT"),
                    ("PHOTO_NOT_CONSENT", "PHOTO_NOT_CONSENT"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        )
    ]
