# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170126_1435'),
        ('events', '0021_auto_20170131_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_covers', to='files.File'),
        ),
    ]
