# Generated by Django 2.1.7 on 2019-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0021_auto_20190302_1448")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_status_type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("infinity", "infinity"),
                    ("open", "open"),
                    ("tba", "tba"),
                ],
                default="normal",
                max_length=50,
            ),
        )
    ]
