# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20170131_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='admin_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
