# Generated by Django 2.1.7 on 2019-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0022_event_event_status_type")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_status_type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("infinity", "infinity"),
                    ("open", "open"),
                    ("tba", "tba"),
                ],
                default="tba",
                max_length=50,
            ),
        )
    ]
