# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_registration_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_notified_overdue_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
