# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_registration_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='presence',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
