# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('events', '0022_registration_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
