# Generated by Django 2.1.7 on 2019-03-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0023_auto_20190311_2057")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_status_type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("infinite", "infinite"),
                    ("open", "open"),
                    ("tba", "tba"),
                ],
                default="tba",
                max_length=50,
            ),
        )
    ]
