# Generated by Django 2.1.7 on 2019-03-26 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0023_auto_20190319_0007")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="(^(?:https?:\\/\\/)?(?:www[.])?(?:youtube[.]com\\/watch[?]v=|youtu[.]be\\/))"
                    )
                ],
            ),
        )
    ]
