# Generated by Django 2.1.7 on 2019-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mazemap_poi',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
