# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_registration_presence'),
        ('events', '0022_auto_20170212_1357'),
    ]

    operations = [
    ]
