# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_merge_20170423_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_captcha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='use_stripe',
            field=models.BooleanField(default=True),
        ),
    ]
