# Generated by Django 2.1.11 on 2019-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190925_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
