# Generated by Django 2.2.13 on 2020-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_registration_payment_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="share_info_flag",
            field=models.BooleanField(default=False),
        ),
    ]
