# Generated by Django 2.2.13 on 2021-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0028_event_use_contact_tracing"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="unregistration_deadline_hours",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
