# Generated by Django 2.2.13 on 2021-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0029_event_unregistration_deadline_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline_hours",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="event",
            name="unregistration_deadline_hours",
            field=models.IntegerField(default=2),
        ),
    ]
