# Generated by Django 4.0.6 on 2022-08-23 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0034_alter_event_event_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="photo_consent",
            new_name="LEGACY_photo_consent",
        ),
    ]
