# Generated by Django 4.0.8 on 2023-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_rename_photo_consent_registration_legacy_photo_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="presence",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PRESENT", "Present"),
                    ("NOT_PRESENT", "Not Present"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
