# Generated by Django 4.0.10 on 2023-09-27 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0036_alter_registration_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="responsible_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
