# Generated by Django 4.0.10 on 2024-02-20 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0038_event_is_foreign_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="use_contact_tracing",
        ),
    ]
