# Generated by Django 4.0.10 on 2024-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0039_remove_event_use_contact_tracing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="presence",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PRESENT", "Present"),
                    ("LATE", "Late"),
                    ("NOT_PRESENT", "Not Present"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
