# Generated by Django 4.0.10 on 2024-09-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_alter_registration_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('company_presentation', 'company_presentation'), ('lunch_presentation', 'lunch_presentation'), ('alternative_presentation', 'alternative_presentation'), ('course', 'course'), ('breakfast_talk', 'breakfast_talk'), ('nexus_event', 'nexus_event'), ('party', 'party'), ('social', 'social'), ('other', 'other'), ('event', 'event')], max_length=50),
        ),
    ]
