# Generated by Django 4.2.16 on 2025-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="show_company_description",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
