# Generated by Django 4.2.16 on 2025-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0042_event_show_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="presence",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PRESENT", "Present"),
                    ("LATE", "Late"),
                    ("NOT_PRESENT", "Not Present"),
                ],
                db_index=True,
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["end_time"], name="events_even_end_tim_a200ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["status", "pool"], name="events_regi_status_68d1ca_idx"
            ),
        ),
    ]
