# Generated by Django 4.2.16 on 2025-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0044_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
