# Generated by Django 5.2.17 on 2026-08-27 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_alter_event_event_type"),
        ("surveys", "0019_alter_survey_template_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationEligibilityCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("can_register_now", models.BooleanField()),
                ("will_be_waiting_list", models.BooleanField()),
                ("is_registration_delayed", models.BooleanField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("no_active_pool", "No active pool"),
                            ("unanswered_surveys", "Unanswered surveys"),
                            ("event_closed", "Event closed"),
                            ("no_photo_consents", "No photo consents"),
                            ("event_not_ready", "Event not ready"),
                            ("no_available_pools", "No available pools"),
                            ("not_open_yet", "Not open yet"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("delay_until", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_eligibilities",
                        to="events.event",
                    ),
                ),
                (
                    "unanswered_surveys",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.survey",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event"), name="uniq_req_elig_cache"
                    )
                ],
            },
        ),
    ]
