# Generated by Django 5.2.17 on 2026-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0048_remove_pool_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="presence_date",
            field=models.DateTimeField(null=True),
        ),
    ]
