# Generated by Django 5.2.17 on 2026-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0048_registrationeligibilitycache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationeligibilitycache",
            name="is_registration_delayed",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="registrationeligibilitycache",
            name="will_be_waiting_list",
            field=models.BooleanField(null=True),
        ),
    ]
