# Generated by Django 4.2.16 on 2025-03-06 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("header", models.CharField(max_length=256)),
                ("subheader", models.CharField(max_length=256)),
                ("link", models.CharField(max_length=512)),
                ("current_public", models.BooleanField(default=False)),
                ("current_private", models.BooleanField(default=False)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("buddyweek2024", "buddyweek2024"),
                            ("gray", "gray"),
                            ("itdageneBlue", "itdageneBlue"),
                            ("lightBlue", "lightBlue"),
                            ("red", "red"),
                            ("white", "white"),
                        ],
                        default="red",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["current_public"], name="banners_ban_current_0b7593_idx"
                    ),
                    models.Index(
                        fields=["current_private"],
                        name="banners_ban_current_675f0e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="banners",
            constraint=models.UniqueConstraint(
                condition=models.Q(("current_public", True)),
                fields=("current_public",),
                name="unique_current_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="banners",
            constraint=models.UniqueConstraint(
                condition=models.Q(("current_private", True)),
                fields=("current_private",),
                name="unique_current_private",
            ),
        ),
    ]
