# Generated by Django 4.2.16 on 2025-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0002_alter_banners_subheader"),
    ]

    operations = [
        migrations.AddField(
            model_name="banners",
            name="countdown_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banners",
            name="countdown_end_message",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
