# Generated by Django 4.2.16 on 2025-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0004_alter_banners_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banners",
            name="color",
            field=models.CharField(
                choices=[
                    ("buddyweek2024", "buddyweek2024"),
                    ("christmas", "christmas"),
                    ("easter", "easter"),
                    ("gray", "gray"),
                    ("itdageneBlue", "itdageneBlue"),
                    ("lightBlue", "lightBlue"),
                    ("red", "red"),
                    ("white", "white"),
                ],
                default="red",
            ),
        ),
    ]
