# Generated by Django 4.2.16 on 2025-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0005_alter_banners_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banners",
            name="link",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
