# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 17:37
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_auto_20160905_2251'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('visible_from', models.DateTimeField()),
                ('visible_to', models.DateTimeField()),
                ('job_type', models.PositiveIntegerField(choices=[(0, 'Full time'), (1, 'Part time'), (2, 'Summer job'), (3, 'Other')])),
                ('workplaces', models.CharField(max_length=100)),
                ('from_year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('to_year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=10)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joblisting_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joblisting_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_manager_name': 'objects',
                'abstract': False,
            },
        ),
    ]
