# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_public'),
        ('joblistings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='images',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
