# Generated by Django 2.0 on 2018-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0005_auto_20171210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
