# Generated by Django 2.0.6 on 2018-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0007_auto_20180205_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='pinned',
        ),
    ]
