# Generated by Django 2.1.7 on 2019-03-11 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("joblistings", "0007_auto_20180205_2103")]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="youtube_url",
            field=models.URLField(
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(?:https?://)?(?:www[.])?(?:youtube[.]com/watch[?]v=|youtu[.]be/)([^&]{11})"
                    )
                ],
            ),
        )
    ]
