# Generated by Django 4.2.16 on 2025-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joblistings", "0010_alter_joblisting_visible_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="rolling_recruitment",
            field=models.BooleanField(default=False),
        ),
    ]
