# Generated by Django 4.2.16 on 2025-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joblistings", "0011_joblisting_rolling_recruitment"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
