# Generated by Django 4.2.16 on 2025-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joblistings", "0012_joblisting_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
