# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_auto_20160225_1809'),
        ('flatpages', '0003_auto_20160406_1835'),
    ]

    operations = [
    ]
