# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
    ]
