# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='waiting_pool',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
    ]
