# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160406_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ingress',
            new_name='description',
        ),
    ]
