# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160421_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='unregistration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('user', 'event')]),
        ),
    ]
