# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160422_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='waiting_pool',
        ),
        migrations.AddField(
            model_name='registration',
            name='waiting_pool',
            field=models.ManyToManyField(null=True, related_name='waiting_registrations', to='events.Pool'),
        ),
    ]
