# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160422_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='waiting_list',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
    ]
