# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160406_1835'),
        ('events', '0007_registration_unregistration_date'),
    ]

    operations = [
    ]
