# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160225_1809'),
        ('events', '0007_auto_20160428_1010'),
    ]

    operations = [
    ]
