# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['registration_date']},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
