# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 15:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160905_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('abakusgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AbakusGroup')),
                ('description_long', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abakusgroup',),
        ),
    ]
