# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_abakusgroup_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='group_type',
            field=models.CharField(choices=[('komite', 'komite'), ('interesse', 'interesse'), ('annen', 'annen')], default='annen', max_length=10),
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='group_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.GroupText'),
        ),
    ]
