# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 18:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_pool_unregistration_deadline'),
        ('users', '0004_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='object_id',
        ),
        migrations.AddField(
            model_name='penalty',
            name='source_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='events.Event'),
            preserve_default=False,
        ),
    ]
