# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_abakusgroup_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakusgroup',
            name='is_interest_group',
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='type',
            field=models.CharField(choices=[('komite', 'komite'), ('interesse', 'interesse'), ('annen', 'annen')], default='annen', max_length=10),
        ),
    ]
