# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170927_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakusgroup',
            name='is_interest_group',
        ),
    ]
