# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170928_2335'),
        ('users', '0005_auto_20170928_2126'),
    ]

    operations = [
    ]
