# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_interestgroup_socialgroup'),
        ('users', '0005_auto_20161108_1837'),
    ]

    operations = [
    ]
