# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20171004_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakusgroup',
            name='is_committee',
        ),
        migrations.RemoveField(
            model_name='abakusgroup',
            name='is_grade',
        ),
        migrations.AlterField(
            model_name='abakusgroup',
            name='type',
            field=models.CharField(choices=[('komite', 'komite'), ('interesse', 'interesse'), ('klasse', 'klasse'), ('annen', 'annen')], default='annen', max_length=10),
        ),
    ]
