# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_auto_20161018_2016'),
        ('comments', '0005_auto_20160905_2251'),
        ('events', '0009_pool_unregistration_deadline'),
        ('articles', '0002_auto_20160905_2251'),
        ('users', '0006_merge_20161118_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialgroup',
            name='abakusgroup_ptr',
        ),
        migrations.DeleteModel(
            name='SocialGroup',
        ),
    ]
