# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '__first__'),
        ('users', '0008_auto_20161119_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.File'),
        ),
    ]
