# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='one',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='two',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
