# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171021_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakusgroup',
            name='internal_email',
        ),
        migrations.RemoveField(
            model_name='abakusgroup',
            name='internal_email_enabled',
        ),
    ]
