# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161221_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=lego.apps.files.models.FileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pictures', to='files.File'),
        ),
    ]
