# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171021_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_lists_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
