# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161221_2327'),
        ('users', '0010_auto_20161214_1947'),
    ]

    operations = [
    ]
