# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_email_lists_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='email_lists_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
