# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20170102_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
