# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

import lego.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_membership_email_lists_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_username',
            field=models.CharField(error_messages={'unique': 'A user has already verified that student username.'}, help_text='30 characters or fewer. Letters, digits and _ only.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters, numbers and _ characters.', 'invalid'), lego.utils.validators.ReservedNameValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and _ only.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters, numbers and _ characters.', 'invalid'), lego.utils.validators.ReservedNameValidator()]),
        ),
    ]
