# Generated by Django 2.0.2 on 2018-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0014_auto_20171210_1610")]

    operations = [
        migrations.AlterField(
            model_name="abakusgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("komite", "komite"),
                    ("interesse", "interesse"),
                    ("klasse", "klasse"),
                    ("annen", "annen"),
                    ("under", "under"),
                ],
                default="annen",
                max_length=10,
            ),
        )
    ]
