# Generated by Django 2.0.2 on 2018-03-24 08:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_abakusgroup_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unanswered_surveys',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], size=None
            ),
        ),
    ]
