# Generated by Django 2.0.3 on 2018-07-29 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_abakusgroup_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_bumped',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='date bumped'
            ),
        ),
    ]
