# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_ldap_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='abakusgroup',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='is_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='is_interest_group',
            field=models.BooleanField(default=False),
        ),
    ]
