# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170425_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='student email address'),
        ),
    ]
