# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_email',
        ),
        migrations.AddField(
            model_name='user',
            name='student_username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user has already verified that student username.'}, help_text='30 characters or fewer. Letters, digits and ./-/_ only.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-._]+$', 'Enter a valid username.  This value may contain only letters, numbers and ./-/_ characters.', 'invalid')]),
        ),
    ]
