# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20170425_2228'),
        ('users', '0017_auto_20170425_1517'),
    ]

    operations = [
    ]
