# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_internal_email'),
        ('users', '0019_auto_20170504_1751'),
    ]

    operations = [
    ]
