# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20170803_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ldap_password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='crypt_password_hash',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='internal_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='email.EmailAddress'),
        ),
    ]
