# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170808_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
