# Generated by Django 2.2.9 on 2020-03-11 23:23

import django.db.models.deletion
from django.db import migrations

import lego.apps.files.models


class Migration(migrations.Migration):
    dependencies = [("users", "0022_user_selected_theme")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=lego.apps.files.models.FileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_pictures",
                to="files.File",
            ),
        )
    ]
