# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0005_auto_20170809_1225'),
        ('users', '0023_auto_20170809_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='abakusgroup',
            name='internal_email',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abakusgroup', to='email.EmailAddress'),
        ),
        migrations.AddField(
            model_name='abakusgroup',
            name='internal_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='internal_email',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='email.EmailAddress'),
        ),
    ]
