# Generated by Django 2.2.13 on 2020-10-20 14:00

from django.db import migrations

import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_auto_20200910_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
