# Generated by Django 2.2.13 on 2020-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20200910_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cookie_consent",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this User have accepted to the cookie pop-up",
            ),
        ),
    ]
