# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models

import lego.apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20170809_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[lego.apps.users.validators.EmailValidatorWithBlacklist(blacklist=['abakus.no'])]),
        ),
    ]
