# Generated by Django 2.2.19 on 2021-04-15 10:04

import django.contrib.postgres.fields
from django.db import migrations, models

import lego.apps.permissions.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_update_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abakusgroup",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=50,
                    validators=[
                        lego.apps.permissions.validators.KeywordPermissionValidator()
                    ],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="permissions",
            ),
        ),
    ]
