# Generated by Django 3.2.12 on 2022-02-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_inactive_notified_counter'),
        ('users', '0031_abakusgroup_active'),
    ]

    operations = [
    ]
