# Generated by Django 3.2.12 on 2022-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_user_inactive_notified_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abakusgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("komite", "komite"),
                    ("interesse", "interesse"),
                    ("styre", "styre"),
                    ("klasse", "klasse"),
                    ("annen", "annen"),
                    ("under", "under"),
                ],
                default="annen",
                max_length=10,
            ),
        ),
    ]
