# Generated by Django 4.0.6 on 2022-08-25 13:19

import django.core.validators
from django.db import migrations, models

import lego.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_membership_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_username",
            field=models.CharField(
                error_messages={
                    "unique": "A user has already verified that student username."
                },
                help_text="30 characters or fewer. Letters, digits and _ only.",
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_\\.]+$",
                        "Enter a valid username. This value may contain only letters, numbers, _ and . characters.",
                        "invalid",
                    ),
                    lego.utils.validators.ReservedNameValidator(),
                ],
            ),
        ),
    ]
