# Generated by Django 4.0.6 on 2022-09-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_photoconsent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photoconsent",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="photoconsent",
            unique_together={("semester", "year", "domain", "user")},
        ),
    ]
