# Generated by Django 4.0.6 on 2022-10-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_alter_photoconsent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abakusgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("komite", "komite"),
                    ("interesse", "interesse"),
                    ("styre", "styre"),
                    ("revy", "revy"),
                    ("klasse", "klasse"),
                    ("annen", "annen"),
                    ("under", "under"),
                ],
                default="annen",
                max_length=10,
            ),
        ),
    ]
