# Generated by Django 4.0.10 on 2023-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_alter_abakusgroup_type"),
    ]

    def update_current_ative_penalties(apps, schema_editor):
        from django.db.models import F

        Penalty = apps.get_model("users", "Penalty")
        Penalty.objects.all().update(activation_time=F("created_at"))

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="activation_time",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="date created"
            ),
        ),
        migrations.RunPython(update_current_ative_penalties),
    ]
