# Generated by Django 4.0.10 on 2023-09-28 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0036_alter_registration_presence"),
        ("users", "0038_alter_abakusgroup_type"),
    ]

    def generate_new_penalties(apps, schema_editor):
        from django.utils import timezone
        from django.utils.timezone import timedelta

        PenaltyGroup = apps.get_model("users", "PenaltyGroup")
        Penalty = apps.get_model("users", "Penalty")
        Event = apps.get_model("events", "Event")

        users_with_penalties = Penalty.objects.filter(
            created_at__gt=timezone.now() - timedelta(days=10)
        ).values_list("user", flat=True)

        Penalty.objects.all().delete()

        for user in users_with_penalties:
            dummy_event = Event.objects.all()[0]
            PenaltyGroup.objects.create(
                user=user,
                reason="Dette er en sammensetting av forrige prikkene",
                source_event=dummy_event,
            )

    operations = [
        migrations.CreateModel(
            name="PenaltyGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("weight", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_groups",
                        to="events.event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="source_event",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="weight",
        ),
        migrations.AddField(
            model_name="penalty",
            name="activation_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="penalty",
            name="penalty_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalties",
                to="users.penaltygroup",
            ),
        ),
        migrations.RunPython(generate_new_penalties),
        migrations.RemoveField(
            model_name="penalty",
            name="user",
        ),
    ]
