# Generated by Django 4.0.10 on 2023-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_user_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_verification_status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
