# Generated by Django 4.0.10 on 2023-04-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_penalty_activation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalty',
            old_name='activation_date',
            new_name='activation_time',
        ),
    ]
