# Generated by Django 4.0.10 on 2024-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_penalty_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abakusgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("komite", "komite"),
                    ("interesse", "interesse"),
                    ("styre", "styre"),
                    ("revy", "revy"),
                    ("klasse", "klasse"),
                    ("annen", "annen"),
                    ("under", "under"),
                    ("ordenen", "ordenen"),
                ],
                default="annen",
                max_length=10,
            ),
        ),
    ]
