# Generated by Django 4.2.16 on 2024-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_alter_abakusgroup_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "member"),
                    ("leader", "leader"),
                    ("co-leader", "co-leader"),
                    ("treasurer", "treasurer"),
                    ("recruiting", "recruiting"),
                    ("development", "development"),
                    ("editor", "editor"),
                    ("retiree", "retiree"),
                    ("media_relations", "media_relations"),
                    ("active_retiree", "active_retiree"),
                    ("alumni", "alumni"),
                    ("webmaster", "webmaster"),
                    ("interest_group_admin", "interest_group_admin"),
                    ("alumni_admin", "alumni_admin"),
                    ("retiree_email", "retiree_email"),
                    ("company_admin", "company_admin"),
                    ("dugnad_admin", "dugnad_admin"),
                    ("trip_admin", "trip_admin"),
                    ("sponsor_admin", "sponsor_admin"),
                    ("social_admin", "social_admin"),
                    ("merch_admin", "merch_admin"),
                    ("hs_representative", "hs_representative"),
                    ("cuddling_manager", "cuddling_manager"),
                    ("photo_admin", "photo_admin"),
                    ("graphic_admin", "graphic_admin"),
                    ("social_media_admin", "social_media_admin"),
                    ("booking_admin", "booking_admin"),
                ],
                default="member",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="membershiphistory",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "member"),
                    ("leader", "leader"),
                    ("co-leader", "co-leader"),
                    ("treasurer", "treasurer"),
                    ("recruiting", "recruiting"),
                    ("development", "development"),
                    ("editor", "editor"),
                    ("retiree", "retiree"),
                    ("media_relations", "media_relations"),
                    ("active_retiree", "active_retiree"),
                    ("alumni", "alumni"),
                    ("webmaster", "webmaster"),
                    ("interest_group_admin", "interest_group_admin"),
                    ("alumni_admin", "alumni_admin"),
                    ("retiree_email", "retiree_email"),
                    ("company_admin", "company_admin"),
                    ("dugnad_admin", "dugnad_admin"),
                    ("trip_admin", "trip_admin"),
                    ("sponsor_admin", "sponsor_admin"),
                    ("social_admin", "social_admin"),
                    ("merch_admin", "merch_admin"),
                    ("hs_representative", "hs_representative"),
                    ("cuddling_manager", "cuddling_manager"),
                    ("photo_admin", "photo_admin"),
                    ("graphic_admin", "graphic_admin"),
                    ("social_media_admin", "social_media_admin"),
                    ("booking_admin", "booking_admin"),
                ],
                default="member",
                max_length=30,
            ),
        ),
    ]
