# Generated by Django 4.2.16 on 2025-03-21 15:47

import django.core.validators
from django.db import migrations, models

import lego.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_membershiphistory_users_membe_user_id_94537a_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="github_username",
            field=models.CharField(
                blank=True,
                help_text="Enter a valid username.",
                max_length=39,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z\\d](?:[a-zA-Z\\d]|-(?=[a-zA-Z\\d])){0,38}$",
                        "Enter a valid GitHub username.",
                    ),
                    lego.utils.validators.ReservedNameValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_id",
            field=models.CharField(
                blank=True,
                help_text="Enter a valid LinkedIn ID.",
                max_length=71,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9-]{0,70}$", "Enter a valid LinkedIn ID."
                    ),
                    lego.utils.validators.ReservedNameValidator(),
                ],
            ),
        ),
    ]
