# Generated by Django 4.2.16 on 2025-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_alter_user_github_username_alter_user_linkedin_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["achievements_score"], name="users_user_achieve_7da505_idx"
            ),
        ),
    ]
