# Generated by Django 4.2.16 on 2025-10-05 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_user_users_user_achieve_7da505_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="command_suggestions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=5,
            ),
        ),
    ]
