# Generated by Django 4.2.16 on 2025-10-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_user_recent_commands"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="recent_commands",
            new_name="command_suggestions",
        ),
    ]
