# Generated by Django 4.2.16 on 2025-11-19 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_user_command_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="christmas_slots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
