# Generated by Django 4.2.16 on 2026-04-15 20:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_user_christmas_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[^\\W\\d_][\\w '\\-\\.]*$", 'Enter a valid name. Names may only contain letters, spaces, hyphens, apostrophes, and periods.', 'invalid', flags=re.RegexFlag['UNICODE'])], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[^\\W\\d_][\\w '\\-\\.]*$", 'Enter a valid name. Names may only contain letters, spaces, hyphens, apostrophes, and periods.', 'invalid', flags=re.RegexFlag['UNICODE'])], verbose_name='last name'),
        ),
    ]
