# Generated by Django 5.2.17 on 2026-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0055_alter_user_linkedin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="abakus_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="users",
                related_query_name="user",
                through="users.Membership",
                through_fields=("user", "abakus_group"),
                to="users.abakusgroup",
            ),
        ),
    ]
