# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restricted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedmail',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
