# Generated by Django 2.2.20 on 2021-05-10 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restricted", "0003_auto_20171210_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrictedmail",
            name="raw_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
