WS_STATUS_CONNECTED = "CONNECTED"
WS_STATUS_CLOSED = "CLOSED"
WS_STATUS_ERROR = "ERROR"

WS_GROUP_TYPES = ["global" "user", "event", "comment"]

WS_GROUP_JOIN_BEGIN = "Websockets.GROUP_JOIN.BEGIN"
WS_GROUP_JOIN_SUCCESS = "Websockets.GROUP_JOIN.SUCCESS"
WS_GROUP_JOIN_FAILURE = "Websockets.GROUP_JOIN.FAILURE"

WS_GROUP_LEAVE_BEGIN = "Websockets.GROUP_LEAVE.BEGIN"
WS_GROUP_LEAVE_SUCCESS = "Websockets.GROUP_LEAVE.SUCCESS"
WS_GROUP_LEAVE_FAILURE = "Websockets.GROUP_LEAVE.FAILURE"
